FROM httpd:2.4.68

COPY deploy/ /usr/local/apache2/htdocs

RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

HEALTHCHECK CMD curl -f http://localhost/ || exit 1