FROM httpd:2.4.68

COPY deploy/ /usr/local/apache2/htdocs/

RUN apt-get update \
    && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

HEALTHCHECK \
--interval=30s \
--timeout=5s \
--retries=3 \
CMD nc -z localhost 80