services:
  nobunaga:
    image: docker:29.7.2-dind
    container_name: nobunaga
    privileged: true
    hostname: nobunaga
    networks:
      samurai_net:
        ipv4_address: 172.19.0.2 

  hideyoshi:
    image: docker:29.7.2-dind
    container_name: hideyoshi
    privileged: true
    hostname: hideyoshi
    networks:
      samurai_net:
        ipv4_address: 172.19.0.3

  tokugawa:
    image: docker:29.7.2-dind
    container_name: tokugawa
    privileged: true
    hostname: tokugawa
    networks:
      samurai_net:
        ipv4_address: 172.19.0.4

  jinsuke:
    image: docker:29.7.2-dind
    container_name: jinsuke
    privileged: true
    hostname: jinsuke
    networks:
      samurai_net:
        ipv4_address: 172.19.0.5

  himura:
    image: docker:29.7.2-dind
    container_name: himura
    privileged: true
    hostname: himura
    networks:
      samurai_net:
        ipv4_address: 172.19.0.6

  sato:
    image: docker:29.7.2-dind
    container_name: sato
    privileged: true
    hostname: sato
    networks:
      samurai_net:
        ipv4_address: 172.19.0.7

  musashi:
    image: docker:29.7.2-dind
    container_name: musashi
    privileged: true
    hostname: musashi
    networks:
      samurai_net:
        ipv4_address: 172.19.0.8

  kojiro:
    image: docker:29.7.2-dind
    container_name: kojiro
    privileged: true
    hostname: kojiro
    networks:
      samurai_net:
        ipv4_address: 172.19.0.9

  masamune:
    image: docker:29.7.2-dind
    container_name: masamune
    privileged: true
    hostname: masamune
    networks:
      samurai_net:
        ipv4_address: 172.19.0.10 

networks:
  samurai_net:
    name: samurai_net
    ipam:
      config:
        - subnet: 172.19.0.0/24