services:
  nobunaga:
    image: docker:29.7.2-dind
    container_name: nobunaga
    privileged: true
    hostname: nobunaga
    networks:
      - samurai_net

  hideyoshi:
    image: docker:29.7.2-dind
    container_name: hideyoshi
    privileged: true
    hostname: hideyoshi
    networks:
      - samurai_net

  tokugawa:
    image: docker:29.7.2-dind
    container_name: tokugawa
    privileged: true
    hostname: tokugawa
    networks:
      - samurai_net

  jinsuke:
    image: docker:29.7.2-dind
    container_name: jinsuke
    privileged: true
    hostname: jinsuke
    networks:
      - samurai_net

  himura:
    image: docker:29.7.2-dind
    container_name: himura
    privileged: true
    hostname: himura
    networks:
      - samurai_net

  sato:
    image: docker:29.7.2-dind
    container_name: sato
    privileged: true
    hostname: sato
    networks:
      - samurai_net

  musashi:
    image: docker:29.7.2-dind
    container_name: musashi
    privileged: true
    hostname: musashi
    networks:
      - samurai_net

  kojiro:
    image: docker:29.7.2-dind
    container_name: kojiro
    privileged: true
    hostname: kojiro
    networks:
      - samurai_net

  masamune:
    image: docker:29.7.2-dind
    container_name: masamune
    privileged: true
    hostname: masamune
    networks:
      - samurai_net  

networks:
  samurai_net:
    name: samurai_net