services:
  website:
    image: static-we:1.0
    build:
      context: .
      dockerfile: Dockerfile.development
      labels:
        maintainer: "Boby"
        version: "1.0"
        description: "Backend API service"
    ports:
      - "8008:80"
    environment:
      NAME: "Boby Widjaja"
      JOB: "Developer"
      DEPARTMENT: "IT"