services:
  my_postgres:
    image: postgres:17.10
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: mystore
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    deploy:
      replicas: 1
volumes:
  postgres_volume:
    external: true
secrets:
  postgres_user:
    file: ./postgres_user.txt
  postgres_password:
    file: ./postgres_password.txt