services:
  helloWorld:
    container_name: hello-world-container
    image: hello-world:latest

  myFedora:
    container_name: fedora-container
    image: fedora:44
    command: sleep infinity

  myUbuntu:
    container_name: ubuntu-container
    image: 'ubuntu:26.04'
    command: sleep infinity