# Menggunakan JDK image (Java Development Kit), dimana kita akan menggunakan Build Toolnya
# Kita akan menggunakan directory bernama app, directory ini akan berada 1 dibawah root. Bila app directory tidak ada, kita otomatis akan membuatnya.
# Copy seluruh source code dari directory HelloWorld ke app directory
# Jalankan javac untuk compile java ke dalam bentuk Main.class
#   -d artinya Destination Directory, hasil Main.class akan ditempatkan di out directory
#   src/Main.java adalah source code yang dipakai untuk melakukan compile
# Jar command disediakan JDK untuk membuat jar artifact
#   --create adalah option untuk membuat file jar baru
#   --file adalah option yang digunakan untuk menentukan nama dari file jar baru ini.
#   --main-class adalah option menentukan class main dari app javanya.
#   -C adalah option yang artinya Change current Directory (sama seperti WORKDIR pada dockerfile instruction)
#       diarahkan ke folder out untuk memproses jar dari hasil compile di directory ini.

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY /HelloWorld .
RUN javac -d out src/Main.java
RUN jar --create \
    --file app.jar \
    --main-class Main \
    -C out .
CMD ["tail", "-f", "/dev/null"]